todo/tasks/urls.py
from django.urls import path

from .views import done_state_view, form_view, list_view


app_name = "bookmarkman"
urlpatterns = [
    path("", list_view, name="list"),
    path("add/", form_view, name="add"),
    path("<int:pk>/", form_view, name="edit"),
    path(
        "done/<int:pk>/",
        done_state_view,
        name="done",
        kwargs={"done_state": True},
    ),
    path(
        "not_done/<int:pk>/",
        done_state_view,
        name="not_done",
        kwargs={"done_state": False},
    ),
]

todo/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.tasks.urls", namespace="tasks")),
]

# Serve static files
if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  # type: ignore
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # type: ignore

todo/tasks/models.py
from django.db import models


class TaskQuerySet(models.QuerySet):
    def done(self):
        return self.filter(done=True)

    def not_done(self):
        return self.filter(done=False)


class Task(models.Model):
    label = models.CharField(max_length=255)
    done = models.BooleanField(default=False)

    objects = TaskQuerySet.as_manager()

    class Meta:
        ordering = ("pk",)

    def __str__(self):
        return self.label

todo/tasks/forms.py
from django.forms import ModelForm

from .models import Task


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ("label",)

todo/tasks/views.py
from functools import wraps
from typing import Any

from django.shortcuts import get_object_or_404, redirect, render

from .forms import TaskForm
from .models import Task


def check_htmx(fn):
    """
    Decorator to check if the request is from htmx, and add a flag to the request if it
    is.

    For function-based views like this, this would normally be done in middleware,
    probably using django-htmx.

    For class-based views you'd probably then want to add a check to get_template_name()
    and then pick up partial_template_name from a class attribute
    """

    @wraps(fn)
    def is_htmx(request, *args, **kwargs):
        # htmx sets the HX-Request header to "true" when it's initiating the request
        if request.headers.get("HX-Request", "false") == "true":
            request.is_htmx = True
        else:
            request.is_htmx = False
        return fn(request, *args, **kwargs)

    return is_htmx


@check_htmx
def list_view(request):
    qs = Task.objects.all()

    filter_done: bool | None
    match request.GET.get("done"):
        case "true":
            filter_done = True
            qs = qs.done()
        case "false":
            filter_done = False
            qs = qs.not_done()
        case _:
            filter_done = None

    context: dict[str, Any] = {
        "tasks": qs,
        "filter_done": filter_done,
    }
    return render(
        request,
        template_name=(
            # If this came from htmx render the partial template, otherwise render the
            # full template - which inherits from base.html and includes the partial.
            "tasks/partials/list.html"
            if request.is_htmx
            else "tasks/list.html"
        ),
        context=context,
    )


@check_htmx
def form_view(request, pk: int | None = None):
    task = None if pk is None else get_object_or_404(Task, pk=pk)
    context: dict[str, Any] = {
        "task": task,
    }

    form = TaskForm(request.POST or None, instance=task)
    if form.is_valid():
        context["task"] = form.save()

        # Normally when you submit a form you want to send the user on to a new page
        # with a redirect to avoid refresh re-submissions. If the request comes from
        # htmx, we can just return a render of the new task
        if request.is_htmx:
            return render(request, "tasks/partials/list-task.html", context=context)
        else:
            return redirect("tasks:list")
    else:
        context["form"] = form

        return render(
            request,
            template_name=(
                "tasks/partials/list-form.html"
                if request.is_htmx
                else "tasks/form.html"
            ),
            context=context,
        )


@check_htmx
def done_state_view(request, pk: int, done_state: bool):
    task = get_object_or_404(Task, pk=pk)
    if task.done != done_state:
        task.done = done_state
        task.save()

    return render(
        request,
        template_name=(
            "tasks/partials/list-task.html"
            if request.is_htmx
            else "tasks/done_state.html"
        ),
        context={
            "task": task,
        },
    )

templates/base.html
{% load static %}<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Tasks</title>
  <style>
    body, [type="submit"] {
      font-family: Charter, 'Bitstream Charter', 'Sitka Text', Cambria, serif;
      font-size: 1rem;
    }

    article {
      max-width: 600px;
      margin: auto;
    }

    ul.buttons {
      display: flex;
      gap: 1rem;
      list-style: none;
      margin: 2rem 0;
      padding: 0;
    }
    ul.buttons a,
    [type="submit"] {
      background: #115599;
      color: white;
      padding: 0.5rem 1rem;
      border-radius: 4px;
      font-weight: bold;
      text-decoration: none;
    }
    ul.buttons a:hover,
    [type="submit"]:hover {
      background: #66aaee;
    }
    [type="submit"] {
      border: 0;
      cursor: pointer;
    }
    {% block extra_style %}{% endblock %}
  </style>
  <script src="{% static "htmx-1.9.2.js" %}" defer="true"></script>
</head>
<body>
  <article>
    <h1>{% block title %}{% endblock %}</h1>

    {% block content %}{% endblock %}
  </article>
</body>
</html>

templates/tasks/done_state.html
{% extends "base.html" %}

{% block title %}Task is {% if not task.done %}not{% endif %} done{% endblock %}

{% block content %}

<p>The task is now marked as {% if not task.done %}not{% endif %} done:</p>

<blockquote>
  {{ task.label }}
</blockquote>

<ul class="buttons">
  <li><a href="{% url "tasks:list" %}">Return to tasks</a></li>
</ul>

{% endblock %}

templates/tasks/form.html
{% comment %}
This form is only rendered for users who don't have htmx. In practice we should merge
this and the partials/list-form - developers will normally just be using htmx, so as it
stands there's a high risk this will get forgotten about when the partial list-form is
made more complicated.
{% endcomment %}

{% extends "base.html" %}

{% block title %}{% if task %}Edit{% else %}Add{% endif %} task{% endblock %}

{% block content %}

<form action="." method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Save">
</form>

{% endblock %}

templates/tasks/list.html
{% extends "base.html" %}

{% block title %}Tasks{% endblock %}

{% block extra_style %}
/* Basic task list styling */
ul.tasks {
  list-style:none;
  margin: 0;
  padding: 0;
}
ul.tasks li {
  display: flex;
  padding: 1rem 0.5rem;
  background: #f8f8f8;
}
ul.tasks li:nth-child(even) {
  background: #f0f0f0;
}

/* Done tasks have strikethrough */
ul.tasks li.done .task {
  text-decoration: line-through;
}

/* Link and button styling */
ul.tasks a {
  color: #333;
  text-decoration: none;
}
ul.tasks a:hover {
  text-decoration: underline;
}
ul.tasks a.button {
  margin-left: auto;
  color: #115599;
}
ul.tasks a.button:hover {
  color: #6699aa;
}

/* Style the task form when we're using HTMX */
ul.tasks li form {
  display: flex;
  flex: 1 1 auto;
  align-items: center;
  gap: 2rem;
}
ul.tasks li form [type="text"] {
  margin: 0;
  flex: 1 1 auto;
}
ul.tasks [type="submit"] {
  flex: 0 0 auto;
  margin-left: auto;
}
{% endblock %}

{% block content %}

{% include "tasks/partials/list.html" %}

<ul class="buttons">
  <li>
    <a
      href="{% url "tasks:add" %}"
      hx-get="{% url "tasks:add" %}"
      hx-target=".tasks"
      hx-swap="beforeend"
    >Add task</a>
  </li>
</ul>

{% endblock %}

templates/tasks/partials/list-form.html
{% comment %}
This is the only partial which isn't used by the non-js version of the site; technically
we could have merged the HTML form, but the differences between them would have
cluttered that template.
{% endcomment %}

<li>
  <form method="post">
    {% csrf_token %}
    {{ form.label }}
    <button
      type="submit"
      class="button"
      hx-post="{% if task %}{% url "tasks:edit" pk=task.pk %}{% else %}{% url "tasks:add" %}{% endif %}"
      hx-target="closest li"
      hx-swap="outerHTML"
    >Save</button>
  </form>
</li>

templates/tasks/partials/list-task.html
<li {% if task.done %} class="done"{% endif %}>
  {# Task label doubles as edit; htmx swaps for a form #}
  <a
    class="task"
    href="{% url "tasks:edit" pk=task.pk %}"
    hx-get="{% url "tasks:edit" pk=task.pk %}"
    hx-target="closest li"
    hx-swap="outerHTML"
  >{{ task.label }}</a>

  {# Status toggles #}
  {% if not task.done %}
    <a
      class="button"
      href="{% url "tasks:done" pk=task.pk %}"
      hx-get="{% url "tasks:done" pk=task.pk %}"
      hx-target="closest li"
      hx-swap="outerHTML"
    >Mark as done</a>
  {% else %}
    <a
      class="button"
      href="{% url "tasks:not_done" pk=task.pk %}"
      hx-get="{% url "tasks:not_done" pk=task.pk %}"
      hx-target="closest li"
      hx-swap="outerHTML"
    >Mark as not done</a>
  {% endif %}
</li>

templates/tasks/partials/list.html
<ul class="buttons" id="controls" hx-swap-oob="true">
  {% if filter_done is True or filter_done is False %}
    <li>
      <a
        href="{% url "tasks:list" %}"
        hx-boost="true"
        hx-target=".tasks"
      >Show all</a>
    </li>
  {% endif %}

  {% if filter_done is not True %}
    <li>
      <a
        href="{% url "tasks:list" %}?done=true"
        hx-boost="true"
        hx-target=".tasks"
      >Only show done</a>
    </li>
  {% endif %}

  {% if filter_done is not False %}
    <li>
      <a
        href="{% url "tasks:list" %}?done=false"
        hx-boost="true"
        hx-target=".tasks"
      >Only show not done</a>
    </li>
  {% endif %}
</ul>

<ul class="tasks">
{% for task in tasks %}
  {% include "tasks/partials/list-task.html" %}
{% endfor %}
</ul>